### ISSUE TITLE
[Eyes test not started] : Error: failed to render screenshot - Occurs randomly resulting in test failures

### ISSUE THREAD

**Issue by traviscrist** [applitools/eyes-cypress#18]
Lately on our applitools cypress eyes test they randomly fail with the error: 
```[Eyes test not started] : Error: failed to render screenshot```
Rerunning them sometimes works and other times it fails. The log indicates that a request to applitools is timing out which I have posted below. 

Are there any ways to resolve this issue? 

Thanks

Log: 
```
019-04-11T18:03:06Z Eyes: [VERBOSE] {} (): ServerConnector.render will now post call to https://render-wus.applitools.com/render with params {}
2019-04-11T18:03:06Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:06Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:06Z Eyes: [VERBOSE] {} (): ServerConnector.render - result OK, status code 200, url https://render-wus.applitools.com/render
2019-04-11T18:03:06Z Eyes: [VERBOSE] {} ServerConnector.render(): ServerConnector.render - post succeeded RunningRender { {"renderId":"6878b2e1-c1d5-4171-9958-369eb63a102d","jobId":"cdb0c80d-0019-40fc-84bb-74e60f710a89","renderStatus":"rendering"} }
2019-04-11T18:03:06Z Eyes: [LOG    ] {} (): render request complete for 6878b2e1-c1d5-4171-9958-369eb63a102d. test=Sign up stepCount #4 tag=Extension Download page sizeMode=full-page browser: {"width":1024,"height":768,"name":"chrome"}
2019-04-11T18:03:06Z Eyes: [LOG    ] {} (): [waitForRenderedStatus] waiting for 6878b2e1-c1d5-4171-9958-369eb63a102d to be rendered
2019-04-11T18:03:06Z Eyes: [LOG    ] {} (): [getRenderStatus] adding job for 6878b2e1-c1d5-4171-9958-369eb63a102d isRunning=true
2019-04-11T18:03:07Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:07Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:08Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:08Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:09Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:09Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:10Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:10Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:11Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:11Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:12Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:12Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:13Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:13Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:14Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:14Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:15Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:15Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:16Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:16Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:17Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:17Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:18Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:18Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:19Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:19Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:20Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:20Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:21Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:21Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:22Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:22Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:23Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:23Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:24Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:24Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:25Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:25Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:26Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:26Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:27Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:27Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:28Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:28Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:29Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:29Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:30Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:30Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:31Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:31Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:32Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:32Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:33Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:33Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:34Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:34Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:35Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:35Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:36Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:36Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:37Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:37Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:38Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:38Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:39Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:39Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:40Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:40Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:41Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:41Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:42Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:42Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:43Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:43Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:44Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:44Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:45Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:45Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:46Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:46Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:47Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:47Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:48Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:48Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:49Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:49Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:50Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:50Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:51Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:51Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:52Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:52Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:53Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:53Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:54Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:54Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:55Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:55Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:56Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:56Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:57Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:57Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:58Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:58Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:03:59Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:03:59Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:00Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:00Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:01Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:01Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:02Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:02Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:03Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:03Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:04Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:04Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:05Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:05Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:06Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:06Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:07Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:07Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:08Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:08Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:09Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:09Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:10Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:10Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:11Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:11Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:12Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:12Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:13Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:13Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:14Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:14Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:15Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:15Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:16Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:16Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:17Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:17Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:18Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:18Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:19Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:19Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:20Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:20Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:21Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:21Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:22Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:22Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:23Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:23Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:24Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:24Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:25Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:25Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:26Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:26Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:27Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:27Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:28Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:28Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:29Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:29Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:30Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:30Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:31Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:31Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:32Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:32Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:33Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:33Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:34Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:34Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:35Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:35Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:36Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:36Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:37Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:37Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:38Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:38Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:39Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:39Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:40Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:40Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:41Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:41Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:42Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:42Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:43Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:43Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:44Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:44Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:45Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:45Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:46Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:46Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:47Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:47Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:48Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:48Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:49Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:49Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:50Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:50Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:51Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:51Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:52Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:52Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:53Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:53Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:54Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:54Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:55Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:55Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:56Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:56Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:57Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:57Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:04:59Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:04:59Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:05:00Z Eyes: [LOG    ] {} (): ServerConnector.renderStatus - post failed on https://render-wus.applitools.com/render-status: connect ETIMEDOUT 104.196.248.157:443 with params {}
2019-04-11T18:05:00Z Eyes: [LOG    ] {} (): [getRenderStatus] error during getRenderStatus: Error: connect ETIMEDOUT 104.196.248.157:443
2019-04-11T18:05:00Z Eyes: [LOG    ] {} (): [waitForRenderedStatus] error during getRenderStatus for 3ac2c88b-9c54-4ac4-b23e-10c6d713d017: Error: connect ETIMEDOUT 104.196.248.157:443
2019-04-11T18:05:00Z Eyes: [LOG    ] {} (): [waitForRenderedStatus] error during getRenderStatus for d0739b41-7145-40a2-b89f-605106d46351: Error: connect ETIMEDOUT 104.196.248.157:443
2019-04-11T18:05:00Z Eyes: [LOG    ] {} (): [waitForRenderedStatus] error during getRenderStatus for 67f3424e-2cb7-477f-8390-b902cdecd065: Error: connect ETIMEDOUT 104.196.248.157:443
2019-04-11T18:05:00Z Eyes: [LOG    ] {} (): aborting checkWindow becuase render status failed
2019-04-11T18:05:00Z Eyes: [LOG    ] {} (): error set in test Sign up Error: failed to render screenshot 3ac2c88b-9c54-4ac4-b23e-10c6d713d017
    at getRenderStatusJob (/usr/src/app/node_modules/@applitools/visual-grid-client/src/sdk/waitForRenderedStatus.js:25:25)
    at getRenderStatusJob (/usr/src/app/node_modules/@applitools/visual-grid-client/src/sdk/waitForRenderedStatus.js:32:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
2019-04-11T18:05:00Z Eyes: [LOG    ] {} (): aborting checkWindow after render status finished
2019-04-11T18:05:00Z Eyes: [LOG    ] {} (): aborting checkWindow after render status finished
2019-04-11T18:05:00Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd timeout
2019-04-11T18:05:00Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd, timeout=240000
2019-04-11T18:05:00Z Eyes: [LOG    ] {} (): [getRenderStatus] render status job (1): 6878b2e1-c1d5-4171-9958-369eb63a102d
2019-04-11T18:05:00Z Eyes: [VERBOSE] {} ServerConnector.renderStatusById(): ServerConnector.renderStatus called for render: 6878b2e1-c1d5-4171-9958-369eb63a102d
2019-04-11T18:05:00Z Eyes: [VERBOSE] {} (): ServerConnector.renderStatus will now post call to https://render-wus.applitools.com/render-status with params {}```

 ✖ [Eyes test not started] : Error: failed to render screenshot 3ac2c88b-9c54-4ac4-b23e-10c6d713d017
    at /usr/src/app/node_modules/@applitools/eyes-cypress/src/plugin/waitForBatch.js:25:13

**Comment by danielschwartz85** [comment]
@traviscrist thanks for issue - checking, will update..

**Comment by traviscrist** [comment]
@danielschwartz85 your colleague Zach mentioned that a solution may be to add the following to each test:
```
afterEach(() => {
  cy.eyesClose();
  cy.reload();
})
```

I'll try that out today, I just have not had a moment to see if it resolves the issue. 

Thanks!

**Comment by danielschwartz85** [comment]
Hi @traviscrist,  did the reload() solve the issue ?

**Comment by igor-starostenko-ag** [comment]
`cy.reload()` helped in my case. I've been getting random errors in the after hook like:
`[Eyes test not started] : Error: Request failed with status code 400 (System.ArgumentNullException ['startInfo.Environment.DisplaySize' is null])`

**Comment by danielschwartz85** [comment]
Ok cool, that issue is known and fixed now, please update eyes-cypress.
closing..
