### ISSUE TITLE
Error: IllegalArgument: webhook is null or empty

### ISSUE THREAD

**Issue by samantgr** [applitools/eyes-cypress#21]
We are getting `Error: IllegalArgument: webhook is null or empty` during cy.eyesCheckWindow(). 

Here is the test:
`context('Tests', function() {
  afterEach(() => {
    // cy.pause()
    cy.eyesClose()
  });
   it('Test', function() {
    // cy.visit(Cypress.env('qs'))
    cy.visit('http://localhost:3000/?productId=1156')
    cy.eyesOpen({
      browser: [{width: 1024, height: 768, name: 'chrome'}],
      batchName: 'Test',
    })
    cy.eyesCheckWindow('Entry Form')
  })
})`

Detailed log output:
`2019-06-26T19:28:22Z Eyes: [LOG    ] {} (): [handlers] creating handlers with the following config: {"concurrency":1"agentId":"eyes-cypress/3.6.34""appName":"Application""showLogs":true"apiKey":"xxxxxxxxxxxx""serverUrl":"https://applitools.cloud.company.com""matchLevel":"Strict""saveDebugData":true}
2019-06-26T19:28:22Z Eyes: [LOG    ] {} Object.<init>(): eyes-cypress plugin running with config: {"concurrency":1"agentId":"eyes-cypress/3.6.34""appName":"Application""showLogs":true"apiKey":"xxxxxxxxxxxx""serverUrl":"https://applitools.cloud.company.com""matchLevel":"Strict""saveDebugData":true}
2019-06-26T19:28:22Z Eyes: [LOG    ] {} (): starting plugin server
2019-06-26T19:28:22Z Eyes: [LOG    ] {} Server.<init>(): plugin server running at port: 54585
2019-06-26T19:28:25Z Eyes: [LOG    ] {} (): [server] eyes api: batchStart viewportuserAgent
2019-06-26T19:28:25Z Eyes: [LOG    ] {} Object.batchStart(): [handlers] batchStart with data {"viewport":{"width":1000"height":660}"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML like Gecko) Chrome/75.0.3770.100 Safari/537.36"}
  Tests
2019-06-26T19:28:26Z Eyes: [LOG    ] {} (): [server] eyes api: batchStart viewportuserAgent
2019-06-26T19:28:26Z Eyes: [LOG    ] {} Object.batchStart(): [handlers] batchStart with data {"viewport":{"width":1000"height":660}"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML like Gecko) Chrome/75.0.3770.100 Safari/537.36"}
2019-06-26T19:28:27Z Eyes: [LOG    ] {} (): [server] eyes api: open testNamebrowserbatchName
2019-06-26T19:28:27Z Eyes: [LOG    ] {} Object.open(): [handlers] open: close=undefined args= {"testName":"Test""browser":[{"width":1024"height":768"name":"chrome"}]"batchName":"Test"}
2019-06-26T19:28:27Z Eyes: [LOG    ] {} (): openEyes: testName=Test browser= [object Object]
2019-06-26T19:28:27Z Eyes: [LOG    ] {} EyesWrapper.setDeviceInfo(): Device Info: Desktop
2019-06-26T19:28:27Z Eyes: [VERBOSE] {} EyesWrapper.setBatch(): setBatch(BatchInfo { {"id":"89b6c83a-9126-4147-94d7-f1ba146affcd""name":"Test""startedAt":"2019-06-26T19:28:27.794Z"} })
2019-06-26T19:28:27Z Eyes: [VERBOSE] {} ServerConnector.renderInfo(): ServerConnector.renderInfo called.
2019-06-26T19:28:27Z Eyes: [VERBOSE] {} (): ServerConnector.renderInfo will now post call to https://applitools.cloud.company.com/api/sessions/renderinfo with params {"apiKey":"xxxxxxxxxxxx"}
2019-06-26T19:28:27Z Eyes: [VERBOSE] {} (): ServerConnector.renderInfo - result OK status code 200 url https://applitools.cloud.company.com/api/sessions/renderinfo
2019-06-26T19:28:27Z Eyes: [VERBOSE] {} ServerConnector.renderInfo(): ServerConnector.renderInfo - post succeeded RenderingInfo { {} }
2019-06-26T19:28:27Z Eyes: [VERBOSE] {} EyesWrapper.openBase(): Agent = eyes-cypress/3.6.34
2019-06-26T19:28:27Z Eyes: [VERBOSE] {} EyesWrapper.openBase(): openBase('Application' 'Test' 'undefined')
2019-06-26T19:28:27Z Eyes: [VERBOSE] {} EyesWrapper._logOpenBase(): Eyes server URL is 'https://applitools.cloud.company.com'
2019-06-26T19:28:27Z Eyes: [VERBOSE] {} EyesWrapper._logOpenBase(): Timeout = 'undefined'
2019-06-26T19:28:27Z Eyes: [VERBOSE] {} EyesWrapper._logOpenBase(): matchTimeout = '2000'
2019-06-26T19:28:27Z Eyes: [VERBOSE] {} EyesWrapper._logOpenBase(): Default match settings = 'ImageMatchSettings { {"matchLevel":"Strict""ignoreCaret":true"useDom":false"enablePatterns":false"ignoreDisplacements":false"ignore":[]"layout":[]"strict":[]"content":[]"floating":[]} }'
2019-06-26T19:28:27Z Eyes: [VERBOSE] {} EyesWrapper._logOpenBase(): FailureReports = 'OnClose'
2019-06-26T19:28:27Z Eyes: [LOG    ] {} Object.open(): [handlers] open finished
2019-06-26T19:28:28Z Eyes: [LOG    ] {} (): [server] PUT resource: http://localhost:3000/static/images/cof-logo.png 12776
2019-06-26T19:28:28Z Eyes: [LOG    ] {} (): [server] PUT resource: http://localhost:3000/static/images/dynamic/upmarket/aspiretravel/card-en.png 122498
2019-06-26T19:28:28Z Eyes: [LOG    ] {} (): [server] PUT resource: http://localhost:3000/static/images/norton-logo.png 11828
2019-06-26T19:28:28Z Eyes: [LOG    ] {} (): [server] PUT resource: http://localhost:3000/static/fonts/Optimist_W_Lt.eot 32142
2019-06-26T19:28:28Z Eyes: [LOG    ] {} (): [server] PUT resource: http://localhost:3000/static/fonts/Optimist_W_Rg.woff2 28388
2019-06-26T19:28:28Z Eyes: [LOG    ] {} (): [server] PUT resource: http://localhost:3000/static/fonts/Optimist_W_Lt.woff2 27852
2019-06-26T19:28:28Z Eyes: [LOG    ] {} (): [server] PUT resource: http://localhost:3000/static/fonts/Optimist_W_Lt.woff 35628
2019-06-26T19:28:28Z Eyes: [LOG    ] {} (): [server] PUT resource: http://localhost:3000/static/fonts/Optimist_W_Rg.eot 32685
2019-06-26T19:28:28Z Eyes: [LOG    ] {} (): [server] PUT resource: http://localhost:3000/static/fonts/Optimist_W_Rg.woff 36144
2019-06-26T19:28:28Z Eyes: [LOG    ] {} (): [server] PUT resource: http://localhost:3000/static/fonts/icomoon.woff 68284
2019-06-26T19:28:28Z Eyes: [LOG    ] {} (): [server] PUT resource: http://localhost:3000/static/fonts/Optimist_W_Lt.ttf 69156
2019-06-26T19:28:28Z Eyes: [LOG    ] {} (): [server] PUT resource: http://localhost:3000/static/fonts/icomoon.ttf 68208
2019-06-26T19:28:28Z Eyes: [LOG    ] {} (): [server] PUT resource: http://localhost:3000/static/fonts/Optimist_W_Rg.ttf 69540
2019-06-26T19:28:28Z Eyes: [LOG    ] {} (): [server] PUT resource: http://localhost:3000/static/fonts/ui-icons.eot 66748
2019-06-26T19:28:28Z Eyes: [LOG    ] {} (): [server] PUT resource: http://localhost:3000/static/fonts/ui-icons.woff 66652
2019-06-26T19:28:28Z Eyes: [LOG    ] {} (): [server] PUT resource: http://localhost:3000/static/fonts/icomoon.svg 247661
2019-06-26T19:28:28Z Eyes: [LOG    ] {} (): [server] PUT resource: http://localhost:3000/static/images/quick-check-header.jpg 47864
2019-06-26T19:28:28Z Eyes: [LOG    ] {} (): [server] PUT resource: http://localhost:3000/static/fonts/ui-icons.svg 240994
2019-06-26T19:28:28Z Eyes: [LOG    ] {} (): [server] PUT resource: http://localhost:3000/static/fonts/icomoon.eot 68372
2019-06-26T19:28:28Z Eyes: [LOG    ] {} (): [server] PUT resource: http://localhost:3000/static/fonts/ui-icons.ttf 66576
2019-06-26T19:28:28Z Eyes: [LOG    ] {} (): [server] PUT resource: http://localhost:3000/96ee6635-babe-4b10-b78f-baa81eb97fff 972536
2019-06-26T19:28:28Z Eyes: [LOG    ] {} (): [server] eyes api: checkWindow urlresourceUrlscdttagblobDataframes
2019-06-26T19:28:28Z Eyes: [LOG    ] {} Object.checkWindow(): [handlers] checkWindow: checkWindow=function
2019-06-26T19:28:28Z Eyes: [LOG    ] {} (): running checkWindow for test Test step #1
    ✓ Test (1614ms)
2019-06-26T19:28:28Z Eyes: [LOG    ] {} (): got render error aborting tests Error: IllegalArgument: webhook is null or empty
    at Function.notNullOrEmpty (/Users/jqp543/workspace/app/acceptance-tests/node_modules/@applitools/eyes-common/lib/utils/ArgumentGuard.js:73:13)
    at new RenderRequest (/Users/jqp543/workspace/app/acceptance-tests/node_modules/@applitools/eyes-sdk-core/lib/renderer/RenderRequest.js:25:19)
    at browsers.map (/Users/jqp543/workspace/app/acceptance-tests/node_modules/@applitools/visual-grid-client/src/sdk/createRenderRequests.js:39:14)
    at Array.map (<anonymous>)
    at createRenderRequests (/Users/jqp543/workspace/app/acceptance-tests/node_modules/@applitools/visual-grid-client/src/sdk/createRenderRequests.js:28:19)
    at startRender (/Users/jqp543/workspace/app/acceptance-tests/node_modules/@applitools/visual-grid-client/src/sdk/checkWindow.js:250:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
2019-06-26T19:28:28Z Eyes: [LOG    ] {} (): [server] eyes api: close
2019-06-26T19:28:28Z Eyes: [LOG    ] {} Object.close(): [handlers] close: openErr=undefined close=function checkWindow=function resources=count:21
2019-06-26T19:28:28Z Eyes: [LOG    ] {} (): closeEyes() fatal error found
2019-06-26T19:28:28Z Eyes: [VERBOSE] {} EyesWrapper._ensureRunningSession(): No running session calling start session...
2019-06-26T19:28:28Z Eyes: [VERBOSE] {} EyesWrapper.startSession(): startSession()
2019-06-26T19:28:28Z Eyes: [VERBOSE] {} EyesWrapper.startSession(): Batch is BatchInfo { {"id":"89b6c83a-9126-4147-94d7-f1ba146affcd""name":"Test""startedAt":"2019-06-26T19:28:27.794Z"} }
2019-06-26T19:28:28Z Eyes: [VERBOSE] {} EyesWrapper.startSession(): Application environment is AppEnvironment { {"displaySize":{"width":1024"height":768}"deviceInfo":"Desktop""osInfo":"Linux""hostingAppInfo":"chrome"} }
2019-06-26T19:28:28Z Eyes: [VERBOSE] {} EyesWrapper.startSession(): Starting server session...
2019-06-26T19:28:28Z Eyes: [VERBOSE] {} ServerConnector.startSession(): ServerConnector.startSession called with: SessionStartInfo { {"agentId":"eyes-cypress/3.6.34""sessionType":"SEQUENTIAL""appIdOrName":"Application""scenarioIdOrName":"Test""batchInfo":{"id":"89b6c83a-9126-4147-94d7-f1ba146affcd""name":"Test""startedAt":"2019-06-26T19:28:27.794Z"}"environment":{"displaySize":{"width":1024"height":768}"deviceInfo":"Desktop""osInfo":"Linux""hostingAppInfo":"chrome"}"defaultMatchSettings":{"matchLevel":"Strict""ignoreCaret":true"useDom":false"enablePatterns":false"ignoreDisplacements":false"ignore":[]"layout":[]"strict":[]"content":[]"floating":[]}"compareWithParentBranch":false"ignoreBaseline":false"render":false"properties":[]} }
2019-06-26T19:28:28Z Eyes: [VERBOSE] {} (): ServerConnector.startSession will now post call to https://applitools.cloud.company.com/api/sessions/running with params {"apiKey":"xxxxxxxxxxxxx"}

2019-06-26T19:28:28Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd
2019-06-26T19:28:28Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd timeout=undefined
2019-06-26T19:28:28Z Eyes: [LOG    ] {} (): Waiting for test results of 1 tests.
2019-06-26T19:28:28Z Eyes: [VERBOSE] {} (): ServerConnector.startSession - result Created status code 201 url https://applitools.cloud.company.com/api/sessions/running
2019-06-26T19:28:28Z Eyes: [VERBOSE] {} ServerConnector.startSession(): ServerConnector.startSession - post succeeded RunningSession { {"id":"MDAwMDAyNTE4NDA3MjM0OTEzOTk~;MDAwMDAyNTE4NDA3MjM0OTEzNTI~""sessionId":"00000251840723491352""batchId":"00000251840723491399""baselineId":"ad0e09d0-a751-4143-ab77-7b925ef43252.54dae0f3-c08b-44ac-9e5e-89d09310c1e1.t_A_WbhXklhG55pLKA4LUCIgX_uAXV3gfkKfd_BAVT4_.""url":"https://applitools.cloud.company.com/app/batches/00000251840723491399/00000251840723491352?accountId=14PVZG2wyEuXzWL5r4Lm_w~~""isNewSession":true} }
2019-06-26T19:28:28Z Eyes: [VERBOSE] {} EyesWrapper.startSession(): Server session ID is MDAwMDAyNTE4NDA3MjM0OTEzOTk~;MDAwMDAyNTE4NDA3MjM0OTEzNTI~
2019-06-26T19:28:28Z Eyes: [LOG    ] {} EyesWrapper.startSession(): --- New test started - 'Test' of 'Application' "AppEnvironment { {"displaySize":{"width":1024"height":768}"deviceInfo":"Desktop""osInfo":"Linux""hostingAppInfo":"chrome"} }
2019-06-26T19:28:28Z Eyes: [VERBOSE] {00000251840723491352} EyesWrapper._ensureRunningSession(): Done!
2019-06-26T19:28:28Z Eyes: [VERBOSE] {00000251840723491352} EyesWrapper.abortIfNotClosed(): Aborting server session...
2019-06-26T19:28:28Z Eyes: [VERBOSE] {00000251840723491352} ServerConnector.stopSession(): ServerConnector.stopSession called with {"isAborted":true"updateBaseline":false} for session: RunningSession { {"id":"MDAwMDAyNTE4NDA3MjM0OTEzOTk~;MDAwMDAyNTE4NDA3MjM0OTEzNTI~""sessionId":"00000251840723491352""batchId":"00000251840723491399""baselineId":"ad0e09d0-a751-4143-ab77-7b925ef43252.54dae0f3-c08b-44ac-9e5e-89d09310c1e1.t_A_WbhXklhG55pLKA4LUCIgX_uAXV3gfkKfd_BAVT4_.""url":"https://applitools.cloud.company.com/app/batches/00000251840723491399/00000251840723491352?accountId=14PVZG2wyEuXzWL5r4Lm_w~~""isNewSession":true} }
2019-06-26T19:28:28Z Eyes: [VERBOSE] {00000251840723491352} (): ServerConnector.stopSession will now post call to https://applitools.cloud.company.com/api/sessions/running/MDAwMDAyNTE4NDA3MjM0OTEzOTk~;MDAwMDAyNTE4NDA3MjM0OTEzNTI~ with params {"aborted":true"updateBaseline":false"apiKey":"bJGURoY7sPaLFmpqdWjx7oUCoudz3ziFEj7pI5byoy4110"}
2019-06-26T19:28:28Z Eyes: [VERBOSE] {00000251840723491352} (): ServerConnector.stopSession - result OK status code 200 url https://applitools.cloud.company.com/api/sessions/running/MDAwMDAyNTE4NDA3MjM0OTEzOTk~;MDAwMDAyNTE4NDA3MjM0OTEzNTI~
2019-06-26T19:28:28Z Eyes: [VERBOSE] {00000251840723491352} ServerConnector.stopSession(): ServerConnector.stopSession - post succeeded TestResults of new test {"id":"00000251840723491352""name":"Test""status":"Failed""appName":"Application""batchName":"Test""batchId":"00000251840723491399""branchName":"default""hostDisplaySize":{"width":1024"height":768}"startedAt":"2019-06-26T19:28:28.600Z""duration":0"isNew":true"isDifferent":false"isAborted":true"appUrls":{"batch":"https://applitools.cloud.company.com/app/test-results/00000251840723491399?accountId=14PVZG2wyEuXzWL5r4Lm_w~~""session":"https://applitools.cloud.company.com/app/test-results/00000251840723491399/00000251840723491352?accountId=14PVZG2wyEuXzWL5r4Lm_w~~"}"apiUrls":{"batch":"https://applitools.cloud.company.com/api/sessions/batches/00000251840723491399""session":"https://applitools.cloud.company.com/api/sessions/batches/00000251840723491399/00000251840723491352"}"stepsInfo":[]"steps":0"matches":0"mismatches":0"missing":0"exactMatches":0"strictMatches":0"contentMatches":0"layoutMatches":0"noneMatches":0}
2019-06-26T19:28:28Z Eyes: [LOG    ] {00000251840723491352} EyesWrapper.abortIfNotClosed(): --- Test aborted.

Important notice: the Applitools visual tests are currently running with a concurrency value of 1.
This means that the visual tests don't run in parallel and therefore are slower. This is the default behavior for free accounts.
If your account does support a higher level of concurrency it's possible to pass a different value by specifying `concurrency:X` in the applitools.config.js file.
For more information on how to configure the concurrency level visit the following link: https://www.npmjs.com/package/@applitools/eyes-cypress#concurrency.
If you are interested in speeding up your visual tests contact sdr@applitools.com to get a trial account and a higher level of concurrency.
2019-06-26T19:28:28Z Eyes: [LOG    ] {} (): errorDigest: diff errors
2019-06-26T19:28:28Z Eyes: [LOG    ] {} (): errorDigest: test errors Error: IllegalArgument: webhook is null or empty
2019-06-26T19:28:29Z Eyes: [LOG    ] {} (): [server] eyes api: batchEnd
2019-06-26T19:28:29Z Eyes: [LOG    ] {} Object.batchEnd(): [handlers] batchEnd timeout=undefined
2019-06-26T19:28:29Z Eyes: [LOG    ] {} (): [server] error in eyes api: Error: Eyes-Cypress detected diffs or errors during execution of visual tests:
       Passed - 0 tests
       Diffs detected - 0 tests
       Errors - 1 tests
         ✖ [Eyes test not started] : Error: IllegalArgument: webhook is null or empty
    at /Users/jqp543/workspace/app/acceptance-tests/node_modules/@applitools/eyes-cypress/src/plugin/waitForBatch.js:25:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  1) "after all" hook for "Test"

  1 passing (4s)
  1 failing

  1) Tests "after all" hook for "Test":
     Error: Eyes-Cypress detected diffs or errors during execution of visual tests:
       Passed - 0 tests
       Diffs detected - 0 tests
       Errors - 1 tests
         ✖ [Eyes test not started] : Error: IllegalArgument: webhook is null or empty

Because this error occurred during a 'after all' hook we are skipping all of the remaining tests.
      at http://localhost:3000/__cypress/tests?p=framework/cypress/support/index.js-740:957:17`

applitools.config.js file
`module.exports = {
  appName: 'Application',
  showLogs: true,
  apiKey: "xxxxx",
  serverUrl: "https://applitools.cloud.company.com",
  matchLevel: 'Strict',
  saveDebugData: true
}`

Please help us resolve this issue.

**Comment by danielschwartz85** [comment]
@samantgr can u share your account id ? (u can get it from the url in the dahsboard or admin panel )
* note - do NOT share you api key

**Comment by samantgr** [comment]
14PVZG2wyEuXzWL5r4Lm_w~~

**Comment by danielschwartz85** [comment]
@samantgr which org are you in ? we are having trouble finding you ?
Also do you know if you have a public or a dedicated cloud for applitools ?

**Comment by samantgr** [comment]
We are on prem cloud.

**Comment by danielschwartz85** [comment]
@samantgr let's continue this in ```support@applitools.com```
Please send an email with the title ```rendering grid on prem```
Thanks.

**Comment by danielschwartz85** [comment]
I am deleting the previous messages so to not confuse other users..

Basically the issue looks like render info returned from "https://applitools.cloud.company.com/" is empty because the customer is onPrem and using the VG.

**Comment by samantgr** [comment]
Thanks!
